#!/usr/bin/env python3
"""Regenerate loops/README.md from the corpus itself.

loops/README.md is a BUILD INPUT (build_site.py parses the starter set and the '≈'
near-duplicate notes out of it), but it was hand-maintained and had drifted badly:
stale counts, only 14 of 38 families listed, dead family names that no longer exist,
and a leaked authoring note. build_library.py, which originally produced it, cannot
run (it points at a deleted scratch path and is frozen at 14 families).

This regenerates the mechanical parts from loops/*.md and preserves the curated
parts (starter set, near-duplicate notes) verbatim, with dead names normalized.

Usage: python3 tools/regen_index.py [--check]
       --check exits non-zero if the file on disk differs from what we'd generate.
"""
from __future__ import annotations
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
LOOPS = ROOT / "loops"
README = LOOPS / "README.md"

# Families were renamed during authoring; the curation notes still used the old
# names, which then rendered on 76 published pages pointing at nothing.
RENAMES = {
    "编排框架": "orchestration-harness",
    "自我批判": "self-critique",
}

# Authoring-process residue that must never ship in a published file.
LEAK_RE = re.compile(r"^\(Note: user standing instruction.*?\)\s*$", re.M | re.S)


def normalize(text: str) -> str:
    for old, new in RENAMES.items():
        text = text.replace(old, new)
    return text


def families() -> list[tuple[str, str, int]]:
    """(key, title, prompt_count) for every real family file, in filename order."""
    out = []
    for path in sorted(LOOPS.glob("*.md")):
        if path.stem == "README" or path.stem.startswith("00"):
            continue
        text = path.read_text(encoding="utf-8")
        title_m = re.search(r"^#\s+(.+)$", text, re.M)
        title = title_m.group(1).strip() if title_m else path.stem
        # count '### N.' headers outside fenced blocks
        count, in_fence = 0, False
        for line in text.splitlines():
            if line.startswith("```"):
                in_fence = not in_fence
            elif not in_fence and re.match(r"^###\s+\d+\.\s+", line):
                count += 1
        out.append((path.stem, title, count))
    return out


def extract_section(text: str, heading: str) -> str:
    """Body of a '## heading' section, up to the next '## ' heading."""
    m = re.search(rf"^{re.escape(heading)}\s*$(.*?)(?=^## |\Z)", text, re.M | re.S)
    return m.group(1).strip("\n") if m else ""


def render() -> str:
    old = README.read_text(encoding="utf-8") if README.exists() else ""
    fams = families()
    total = sum(c for _k, _t, c in fams)

    starter = normalize(extract_section(old, "## Starter set"))
    notes = normalize(extract_section(old, "## Curation notes"))
    notes = LEAK_RE.sub("", notes).strip("\n")

    lines = [
        "# Loop-prompt library",
        "",
        f"**{total} reusable agent-loop prompts** across {len(fams)} loop families. Each is a "
        "copy-pasteable, model-agnostic prompt with an explicit stop condition so an agent "
        "iterates to a goal without looping forever.",
        "",
        "> Generated by `tools/regen_index.py` from `loops/*.md`. Counts and the family list are "
        "derived; the starter set and curation notes below are curated prose. Re-run after adding "
        "or removing prompts — CI checks this file is in sync.",
        "",
        "Start with [loop-engineering principles](00-loop-engineering-principles.md), then browse a family:",
        "",
    ]
    for key, title, count in fams:
        lines.append(f"- **[{title}]({key}.md)** — {count} prompt{'s' if count != 1 else ''}")
    if starter:
        lines += ["", "## Starter set", "", starter]
    if notes:
        lines += ["", "## Curation notes", "", notes]
    return "\n".join(lines).rstrip("\n") + "\n"


def main() -> int:
    new = render()
    if "--check" in sys.argv:
        cur = README.read_text(encoding="utf-8") if README.exists() else ""
        if cur != new:
            print("loops/README.md is OUT OF SYNC with the corpus. Run: python3 tools/regen_index.py")
            return 1
        print("loops/README.md in sync with the corpus")
        return 0
    README.write_text(new, encoding="utf-8")
    fams = families()
    print(f"wrote loops/README.md — {sum(c for *_ , c in fams)} prompts across {len(fams)} families")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
